#!/usr/bin/make -f


# MAKEFILE GENERATED BY QPC
# IF YOU ARE READING THIS AND DID NOT GENERATE THIS FILE WITH QPC,
# IT PROBABLY WILL NOT WORK. DOWNLOAD QPC AND BUILD THE MAKEFILE
# YOURSELF.


# |￣￣￣￣￣￣￣￣|  
# |    make > *    |
# |＿＿＿＿＿＿＿＿|
# (\__/) || 
# (•ㅅ•) || 
# / 　 づ  

# don't mess with this, might break stuff
ifndef $(ARCH)
ARCH = amd64
endif

# change the config with CONFIG=[Debug,Release] to make
ifndef $(CONFIG)
CONFIG = Debug
endif

# edit this in your QPC script configuration/general/compiler
ifndef $(COMPILER)
COMPILER = g++
endif


# COLORS!!!


RED     =[0;31m
CYAN    =[0;36m
GREEN   =[0;32m
NC      =[0m

############################
### BEGIN BUILD TARGETS ###
###########################

ifeq (Debug,$(CONFIG))

ifeq (i386,$(ARCH))

# CREATE OUT DIR
$(shell mkdir -p ../../sidury/bin)

# CREATE BUILD DIR
$(shell mkdir -p ../../obj/engine/Debug)

# SOURCE FILES:

SOURCES = ../src/shared/util.cpp	\
	../src/shared/system.cpp	\
	../src/shared/msgs.cpp	\
	../src/shared/platform.cpp	\
	../src/shared/console.cpp	\
	../src/imgui/imgui_impl_vulkan.cpp	\
	../src/imgui/imgui_demo.cpp	\
	../src/imgui/imgui_widgets.cpp	\
	../src/imgui/imgui_draw.cpp	\
	../src/imgui/imgui.cpp	\
	../src/imgui/imgui_impl_sdl.cpp	\
	../src/imgui/imgui_tables.cpp	\
	../src/core/graphics.cpp	\
	../src/core/audio.cpp	\
	../src/core/main.cpp	\
	../src/core/input.cpp	\
	../src/core/gui.cpp	\
	../src/core/engine.cpp	\
	../src/core/renderer/device.cpp	\
	../src/core/renderer/renderer.cpp	\
	../src/core/renderer/allocator.cpp

#OBJECTS:

OBJECTS = ../../obj/engine/Debug/util.o	\
	../../obj/engine/Debug/system.o	\
	../../obj/engine/Debug/msgs.o	\
	../../obj/engine/Debug/platform.o	\
	../../obj/engine/Debug/console.o	\
	../../obj/engine/Debug/imgui_impl_vulkan.o	\
	../../obj/engine/Debug/imgui_demo.o	\
	../../obj/engine/Debug/imgui_widgets.o	\
	../../obj/engine/Debug/imgui_draw.o	\
	../../obj/engine/Debug/imgui.o	\
	../../obj/engine/Debug/imgui_impl_sdl.o	\
	../../obj/engine/Debug/imgui_tables.o	\
	../../obj/engine/Debug/graphics.o	\
	../../obj/engine/Debug/audio.o	\
	../../obj/engine/Debug/main.o	\
	../../obj/engine/Debug/input.o	\
	../../obj/engine/Debug/gui.o	\
	../../obj/engine/Debug/engine.o	\
	../../obj/engine/Debug/device.o	\
	../../obj/engine/Debug/renderer.o	\
	../../obj/engine/Debug/allocator.o

# MACROS:

OUTNAME = engine

# TARGETS

$(addsuffix .so,$(OUTNAME)): __PREBUILD $(OBJECTS) __PRELINK 
	@echo '$(CYAN)Compiling dynamic library $(OUTNAME).so$(NC)'
	@$(COMPILER) -shared -fPIC $(SOURCES)  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I/home/karl/Desktop/Git-Repos/sidury/chocolate/inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 -o $@
	
# CLEAN TARGET:

clean:
	@echo "Cleaning objects, archives, shared objects, and dynamic libs"
	@rm -f $(wildcard *.o *.a *.so *.dll *.dylib)

.PHONY: clean __PREBUILD __PRELINK __POSTBUILD



#DEPENDENCY TREE:


../../obj/engine/Debug/util.o: ../src/shared/util.cpp
	@echo '$(CYAN)Building Object ../src/shared/util.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/shared/util.cpp -o $@

../../obj/engine/Debug/system.o: ../src/shared/system.cpp
	@echo '$(CYAN)Building Object ../src/shared/system.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/shared/system.cpp -o $@

../../obj/engine/Debug/msgs.o: ../src/shared/msgs.cpp
	@echo '$(CYAN)Building Object ../src/shared/msgs.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/shared/msgs.cpp -o $@

../../obj/engine/Debug/platform.o: ../src/shared/platform.cpp
	@echo '$(CYAN)Building Object ../src/shared/platform.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/shared/platform.cpp -o $@

../../obj/engine/Debug/console.o: ../src/shared/console.cpp
	@echo '$(CYAN)Building Object ../src/shared/console.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/shared/console.cpp -o $@

../../obj/engine/Debug/imgui_impl_vulkan.o: ../src/imgui/imgui_impl_vulkan.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui_impl_vulkan.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui_impl_vulkan.cpp -o $@

../../obj/engine/Debug/imgui_demo.o: ../src/imgui/imgui_demo.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui_demo.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui_demo.cpp -o $@

../../obj/engine/Debug/imgui_widgets.o: ../src/imgui/imgui_widgets.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui_widgets.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui_widgets.cpp -o $@

../../obj/engine/Debug/imgui_draw.o: ../src/imgui/imgui_draw.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui_draw.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui_draw.cpp -o $@

../../obj/engine/Debug/imgui.o: ../src/imgui/imgui.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui.cpp -o $@

../../obj/engine/Debug/imgui_impl_sdl.o: ../src/imgui/imgui_impl_sdl.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui_impl_sdl.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui_impl_sdl.cpp -o $@

../../obj/engine/Debug/imgui_tables.o: ../src/imgui/imgui_tables.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui_tables.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui_tables.cpp -o $@

../../obj/engine/Debug/graphics.o: ../src/core/graphics.cpp
	@echo '$(CYAN)Building Object ../src/core/graphics.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/graphics.cpp -o $@

../../obj/engine/Debug/audio.o: ../src/core/audio.cpp
	@echo '$(CYAN)Building Object ../src/core/audio.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/audio.cpp -o $@

../../obj/engine/Debug/main.o: ../src/core/main.cpp
	@echo '$(CYAN)Building Object ../src/core/main.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/main.cpp -o $@

../../obj/engine/Debug/input.o: ../src/core/input.cpp
	@echo '$(CYAN)Building Object ../src/core/input.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/input.cpp -o $@

../../obj/engine/Debug/gui.o: ../src/core/gui.cpp
	@echo '$(CYAN)Building Object ../src/core/gui.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/gui.cpp -o $@

../../obj/engine/Debug/engine.o: ../src/core/engine.cpp
	@echo '$(CYAN)Building Object ../src/core/engine.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/engine.cpp -o $@

../../obj/engine/Debug/device.o: ../src/core/renderer/device.cpp
	@echo '$(CYAN)Building Object ../src/core/renderer/device.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/renderer/device.cpp -o $@

../../obj/engine/Debug/renderer.o: ../src/core/renderer/renderer.cpp
	@echo '$(CYAN)Building Object ../src/core/renderer/renderer.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/renderer/renderer.cpp -o $@

../../obj/engine/Debug/allocator.o: ../src/core/renderer/allocator.cpp
	@echo '$(CYAN)Building Object ../src/core/renderer/allocator.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/renderer/allocator.cpp -o $@


__PREBUILD:
	



__PRELINK:
	


endif

endif

ifeq (Debug,$(CONFIG))

ifeq (amd64,$(ARCH))

# CREATE OUT DIR
$(shell mkdir -p ../../sidury/bin)

# CREATE BUILD DIR
$(shell mkdir -p ../../obj/engine/Debug)

# SOURCE FILES:

SOURCES = ../src/shared/util.cpp	\
	../src/shared/system.cpp	\
	../src/shared/msgs.cpp	\
	../src/shared/platform.cpp	\
	../src/shared/console.cpp	\
	../src/imgui/imgui_impl_vulkan.cpp	\
	../src/imgui/imgui_demo.cpp	\
	../src/imgui/imgui_widgets.cpp	\
	../src/imgui/imgui_draw.cpp	\
	../src/imgui/imgui.cpp	\
	../src/imgui/imgui_impl_sdl.cpp	\
	../src/imgui/imgui_tables.cpp	\
	../src/core/graphics.cpp	\
	../src/core/audio.cpp	\
	../src/core/main.cpp	\
	../src/core/input.cpp	\
	../src/core/gui.cpp	\
	../src/core/engine.cpp	\
	../src/core/renderer/device.cpp	\
	../src/core/renderer/renderer.cpp	\
	../src/core/renderer/allocator.cpp

#OBJECTS:

OBJECTS = ../../obj/engine/Debug/util.o	\
	../../obj/engine/Debug/system.o	\
	../../obj/engine/Debug/msgs.o	\
	../../obj/engine/Debug/platform.o	\
	../../obj/engine/Debug/console.o	\
	../../obj/engine/Debug/imgui_impl_vulkan.o	\
	../../obj/engine/Debug/imgui_demo.o	\
	../../obj/engine/Debug/imgui_widgets.o	\
	../../obj/engine/Debug/imgui_draw.o	\
	../../obj/engine/Debug/imgui.o	\
	../../obj/engine/Debug/imgui_impl_sdl.o	\
	../../obj/engine/Debug/imgui_tables.o	\
	../../obj/engine/Debug/graphics.o	\
	../../obj/engine/Debug/audio.o	\
	../../obj/engine/Debug/main.o	\
	../../obj/engine/Debug/input.o	\
	../../obj/engine/Debug/gui.o	\
	../../obj/engine/Debug/engine.o	\
	../../obj/engine/Debug/device.o	\
	../../obj/engine/Debug/renderer.o	\
	../../obj/engine/Debug/allocator.o

# MACROS:

OUTNAME = engine

# TARGETS

$(addsuffix .so,$(OUTNAME)): __PREBUILD $(OBJECTS) __PRELINK 
	@echo '$(CYAN)Compiling dynamic library $(OUTNAME).so$(NC)'
	@$(COMPILER) -shared -fPIC $(SOURCES)  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 -o $@
	
# CLEAN TARGET:

clean:
	@echo "Cleaning objects, archives, shared objects, and dynamic libs"
	@rm -f $(wildcard *.o *.a *.so *.dll *.dylib)

.PHONY: clean __PREBUILD __PRELINK __POSTBUILD



#DEPENDENCY TREE:


../../obj/engine/Debug/util.o: ../src/shared/util.cpp
	@echo '$(CYAN)Building Object ../src/shared/util.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/shared/util.cpp -o $@

../../obj/engine/Debug/system.o: ../src/shared/system.cpp
	@echo '$(CYAN)Building Object ../src/shared/system.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/shared/system.cpp -o $@

../../obj/engine/Debug/msgs.o: ../src/shared/msgs.cpp
	@echo '$(CYAN)Building Object ../src/shared/msgs.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/shared/msgs.cpp -o $@

../../obj/engine/Debug/platform.o: ../src/shared/platform.cpp
	@echo '$(CYAN)Building Object ../src/shared/platform.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/shared/platform.cpp -o $@

../../obj/engine/Debug/console.o: ../src/shared/console.cpp
	@echo '$(CYAN)Building Object ../src/shared/console.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/shared/console.cpp -o $@

../../obj/engine/Debug/imgui_impl_vulkan.o: ../src/imgui/imgui_impl_vulkan.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui_impl_vulkan.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui_impl_vulkan.cpp -o $@

../../obj/engine/Debug/imgui_demo.o: ../src/imgui/imgui_demo.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui_demo.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui_demo.cpp -o $@

../../obj/engine/Debug/imgui_widgets.o: ../src/imgui/imgui_widgets.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui_widgets.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui_widgets.cpp -o $@

../../obj/engine/Debug/imgui_draw.o: ../src/imgui/imgui_draw.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui_draw.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui_draw.cpp -o $@

../../obj/engine/Debug/imgui.o: ../src/imgui/imgui.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui.cpp -o $@

../../obj/engine/Debug/imgui_impl_sdl.o: ../src/imgui/imgui_impl_sdl.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui_impl_sdl.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui_impl_sdl.cpp -o $@

../../obj/engine/Debug/imgui_tables.o: ../src/imgui/imgui_tables.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui_tables.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui_tables.cpp -o $@

../../obj/engine/Debug/graphics.o: ../src/core/graphics.cpp
	@echo '$(CYAN)Building Object ../src/core/graphics.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/graphics.cpp -o $@

../../obj/engine/Debug/audio.o: ../src/core/audio.cpp
	@echo '$(CYAN)Building Object ../src/core/audio.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/audio.cpp -o $@

../../obj/engine/Debug/main.o: ../src/core/main.cpp
	@echo '$(CYAN)Building Object ../src/core/main.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/main.cpp -o $@

../../obj/engine/Debug/input.o: ../src/core/input.cpp
	@echo '$(CYAN)Building Object ../src/core/input.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/input.cpp -o $@

../../obj/engine/Debug/gui.o: ../src/core/gui.cpp
	@echo '$(CYAN)Building Object ../src/core/gui.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/gui.cpp -o $@

../../obj/engine/Debug/engine.o: ../src/core/engine.cpp
	@echo '$(CYAN)Building Object ../src/core/engine.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/engine.cpp -o $@

../../obj/engine/Debug/device.o: ../src/core/renderer/device.cpp
	@echo '$(CYAN)Building Object ../src/core/renderer/device.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/renderer/device.cpp -o $@

../../obj/engine/Debug/renderer.o: ../src/core/renderer/renderer.cpp
	@echo '$(CYAN)Building Object ../src/core/renderer/renderer.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/renderer/renderer.cpp -o $@

../../obj/engine/Debug/allocator.o: ../src/core/renderer/allocator.cpp
	@echo '$(CYAN)Building Object ../src/core/renderer/allocator.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/renderer/allocator.cpp -o $@


__PREBUILD:
	



__PRELINK:
	


endif

endif

ifeq (Release,$(CONFIG))

ifeq (i386,$(ARCH))

# CREATE OUT DIR
$(shell mkdir -p ../../sidury/bin)

# CREATE BUILD DIR
$(shell mkdir -p ../../obj/engine/Release)

# SOURCE FILES:

SOURCES = ../src/shared/util.cpp	\
	../src/shared/system.cpp	\
	../src/shared/msgs.cpp	\
	../src/shared/platform.cpp	\
	../src/shared/console.cpp	\
	../src/imgui/imgui_impl_vulkan.cpp	\
	../src/imgui/imgui_demo.cpp	\
	../src/imgui/imgui_widgets.cpp	\
	../src/imgui/imgui_draw.cpp	\
	../src/imgui/imgui.cpp	\
	../src/imgui/imgui_impl_sdl.cpp	\
	../src/imgui/imgui_tables.cpp	\
	../src/core/graphics.cpp	\
	../src/core/audio.cpp	\
	../src/core/main.cpp	\
	../src/core/input.cpp	\
	../src/core/gui.cpp	\
	../src/core/engine.cpp	\
	../src/core/renderer/device.cpp	\
	../src/core/renderer/renderer.cpp	\
	../src/core/renderer/allocator.cpp

#OBJECTS:

OBJECTS = ../../obj/engine/Release/util.o	\
	../../obj/engine/Release/system.o	\
	../../obj/engine/Release/msgs.o	\
	../../obj/engine/Release/platform.o	\
	../../obj/engine/Release/console.o	\
	../../obj/engine/Release/imgui_impl_vulkan.o	\
	../../obj/engine/Release/imgui_demo.o	\
	../../obj/engine/Release/imgui_widgets.o	\
	../../obj/engine/Release/imgui_draw.o	\
	../../obj/engine/Release/imgui.o	\
	../../obj/engine/Release/imgui_impl_sdl.o	\
	../../obj/engine/Release/imgui_tables.o	\
	../../obj/engine/Release/graphics.o	\
	../../obj/engine/Release/audio.o	\
	../../obj/engine/Release/main.o	\
	../../obj/engine/Release/input.o	\
	../../obj/engine/Release/gui.o	\
	../../obj/engine/Release/engine.o	\
	../../obj/engine/Release/device.o	\
	../../obj/engine/Release/renderer.o	\
	../../obj/engine/Release/allocator.o

# MACROS:

OUTNAME = engine

# TARGETS

$(addsuffix .so,$(OUTNAME)): __PREBUILD $(OBJECTS) __PRELINK 
	@echo '$(CYAN)Compiling dynamic library $(OUTNAME).so$(NC)'
	@$(COMPILER) -shared -fPIC $(SOURCES)  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 -o $@
	
# CLEAN TARGET:

clean:
	@echo "Cleaning objects, archives, shared objects, and dynamic libs"
	@rm -f $(wildcard *.o *.a *.so *.dll *.dylib)

.PHONY: clean __PREBUILD __PRELINK __POSTBUILD



#DEPENDENCY TREE:


../../obj/engine/Release/util.o: ../src/shared/util.cpp
	@echo '$(CYAN)Building Object ../src/shared/util.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/shared/util.cpp -o $@

../../obj/engine/Release/system.o: ../src/shared/system.cpp
	@echo '$(CYAN)Building Object ../src/shared/system.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/shared/system.cpp -o $@

../../obj/engine/Release/msgs.o: ../src/shared/msgs.cpp
	@echo '$(CYAN)Building Object ../src/shared/msgs.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/shared/msgs.cpp -o $@

../../obj/engine/Release/platform.o: ../src/shared/platform.cpp
	@echo '$(CYAN)Building Object ../src/shared/platform.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/shared/platform.cpp -o $@

../../obj/engine/Release/console.o: ../src/shared/console.cpp
	@echo '$(CYAN)Building Object ../src/shared/console.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/shared/console.cpp -o $@

../../obj/engine/Release/imgui_impl_vulkan.o: ../src/imgui/imgui_impl_vulkan.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui_impl_vulkan.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui_impl_vulkan.cpp -o $@

../../obj/engine/Release/imgui_demo.o: ../src/imgui/imgui_demo.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui_demo.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui_demo.cpp -o $@

../../obj/engine/Release/imgui_widgets.o: ../src/imgui/imgui_widgets.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui_widgets.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui_widgets.cpp -o $@

../../obj/engine/Release/imgui_draw.o: ../src/imgui/imgui_draw.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui_draw.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui_draw.cpp -o $@

../../obj/engine/Release/imgui.o: ../src/imgui/imgui.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui.cpp -o $@

../../obj/engine/Release/imgui_impl_sdl.o: ../src/imgui/imgui_impl_sdl.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui_impl_sdl.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui_impl_sdl.cpp -o $@

../../obj/engine/Release/imgui_tables.o: ../src/imgui/imgui_tables.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui_tables.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui_tables.cpp -o $@

../../obj/engine/Release/graphics.o: ../src/core/graphics.cpp
	@echo '$(CYAN)Building Object ../src/core/graphics.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/graphics.cpp -o $@

../../obj/engine/Release/audio.o: ../src/core/audio.cpp
	@echo '$(CYAN)Building Object ../src/core/audio.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/audio.cpp -o $@

../../obj/engine/Release/main.o: ../src/core/main.cpp
	@echo '$(CYAN)Building Object ../src/core/main.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/main.cpp -o $@

../../obj/engine/Release/input.o: ../src/core/input.cpp
	@echo '$(CYAN)Building Object ../src/core/input.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/input.cpp -o $@

../../obj/engine/Release/gui.o: ../src/core/gui.cpp
	@echo '$(CYAN)Building Object ../src/core/gui.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/gui.cpp -o $@

../../obj/engine/Release/engine.o: ../src/core/engine.cpp
	@echo '$(CYAN)Building Object ../src/core/engine.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/engine.cpp -o $@

../../obj/engine/Release/device.o: ../src/core/renderer/device.cpp
	@echo '$(CYAN)Building Object ../src/core/renderer/device.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/renderer/device.cpp -o $@

../../obj/engine/Release/renderer.o: ../src/core/renderer/renderer.cpp
	@echo '$(CYAN)Building Object ../src/core/renderer/renderer.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/renderer/renderer.cpp -o $@

../../obj/engine/Release/allocator.o: ../src/core/renderer/allocator.cpp
	@echo '$(CYAN)Building Object ../src/core/renderer/allocator.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/renderer/allocator.cpp -o $@


__PREBUILD:
	



__PRELINK:
	


endif

endif

ifeq (Release,$(CONFIG))

ifeq (amd64,$(ARCH))

# CREATE OUT DIR
$(shell mkdir -p ../../sidury/bin)

# CREATE BUILD DIR
$(shell mkdir -p ../../obj/engine/Release)

# SOURCE FILES:

SOURCES = ../src/shared/util.cpp	\
	../src/shared/system.cpp	\
	../src/shared/msgs.cpp	\
	../src/shared/platform.cpp	\
	../src/shared/console.cpp	\
	../src/imgui/imgui_impl_vulkan.cpp	\
	../src/imgui/imgui_demo.cpp	\
	../src/imgui/imgui_widgets.cpp	\
	../src/imgui/imgui_draw.cpp	\
	../src/imgui/imgui.cpp	\
	../src/imgui/imgui_impl_sdl.cpp	\
	../src/imgui/imgui_tables.cpp	\
	../src/core/graphics.cpp	\
	../src/core/audio.cpp	\
	../src/core/main.cpp	\
	../src/core/input.cpp	\
	../src/core/gui.cpp	\
	../src/core/engine.cpp	\
	../src/core/renderer/device.cpp	\
	../src/core/renderer/renderer.cpp	\
	../src/core/renderer/allocator.cpp

#OBJECTS:

OBJECTS = ../../obj/engine/Release/util.o	\
	../../obj/engine/Release/system.o	\
	../../obj/engine/Release/msgs.o	\
	../../obj/engine/Release/platform.o	\
	../../obj/engine/Release/console.o	\
	../../obj/engine/Release/imgui_impl_vulkan.o	\
	../../obj/engine/Release/imgui_demo.o	\
	../../obj/engine/Release/imgui_widgets.o	\
	../../obj/engine/Release/imgui_draw.o	\
	../../obj/engine/Release/imgui.o	\
	../../obj/engine/Release/imgui_impl_sdl.o	\
	../../obj/engine/Release/imgui_tables.o	\
	../../obj/engine/Release/graphics.o	\
	../../obj/engine/Release/audio.o	\
	../../obj/engine/Release/main.o	\
	../../obj/engine/Release/input.o	\
	../../obj/engine/Release/gui.o	\
	../../obj/engine/Release/engine.o	\
	../../obj/engine/Release/device.o	\
	../../obj/engine/Release/renderer.o	\
	../../obj/engine/Release/allocator.o

# MACROS:

OUTNAME = engine

# TARGETS

$(addsuffix .so,$(OUTNAME)): __PREBUILD $(OBJECTS) __PRELINK 
	@echo '$(CYAN)Compiling dynamic library $(OUTNAME).so$(NC)'
	@$(COMPILER) -shared -fPIC $(SOURCES)  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 -o $@
	
# CLEAN TARGET:

clean:
	@echo "Cleaning objects, archives, shared objects, and dynamic libs"
	@rm -f $(wildcard *.o *.a *.so *.dll *.dylib)

.PHONY: clean __PREBUILD __PRELINK __POSTBUILD



#DEPENDENCY TREE:


../../obj/engine/Release/util.o: ../src/shared/util.cpp
	@echo '$(CYAN)Building Object ../src/shared/util.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/shared/util.cpp -o $@

../../obj/engine/Release/system.o: ../src/shared/system.cpp
	@echo '$(CYAN)Building Object ../src/shared/system.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/shared/system.cpp -o $@

../../obj/engine/Release/msgs.o: ../src/shared/msgs.cpp
	@echo '$(CYAN)Building Object ../src/shared/msgs.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/shared/msgs.cpp -o $@

../../obj/engine/Release/platform.o: ../src/shared/platform.cpp
	@echo '$(CYAN)Building Object ../src/shared/platform.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/shared/platform.cpp -o $@

../../obj/engine/Release/console.o: ../src/shared/console.cpp
	@echo '$(CYAN)Building Object ../src/shared/console.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/shared/console.cpp -o $@

../../obj/engine/Release/imgui_impl_vulkan.o: ../src/imgui/imgui_impl_vulkan.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui_impl_vulkan.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui_impl_vulkan.cpp -o $@

../../obj/engine/Release/imgui_demo.o: ../src/imgui/imgui_demo.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui_demo.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui_demo.cpp -o $@

../../obj/engine/Release/imgui_widgets.o: ../src/imgui/imgui_widgets.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui_widgets.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui_widgets.cpp -o $@

../../obj/engine/Release/imgui_draw.o: ../src/imgui/imgui_draw.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui_draw.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui_draw.cpp -o $@

../../obj/engine/Release/imgui.o: ../src/imgui/imgui.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui.cpp -o $@

../../obj/engine/Release/imgui_impl_sdl.o: ../src/imgui/imgui_impl_sdl.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui_impl_sdl.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui_impl_sdl.cpp -o $@

../../obj/engine/Release/imgui_tables.o: ../src/imgui/imgui_tables.cpp
	@echo '$(CYAN)Building Object ../src/imgui/imgui_tables.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/imgui/imgui_tables.cpp -o $@

../../obj/engine/Release/graphics.o: ../src/core/graphics.cpp
	@echo '$(CYAN)Building Object ../src/core/graphics.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/graphics.cpp -o $@

../../obj/engine/Release/audio.o: ../src/core/audio.cpp
	@echo '$(CYAN)Building Object ../src/core/audio.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/audio.cpp -o $@

../../obj/engine/Release/main.o: ../src/core/main.cpp
	@echo '$(CYAN)Building Object ../src/core/main.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/main.cpp -o $@

../../obj/engine/Release/input.o: ../src/core/input.cpp
	@echo '$(CYAN)Building Object ../src/core/input.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/input.cpp -o $@

../../obj/engine/Release/gui.o: ../src/core/gui.cpp
	@echo '$(CYAN)Building Object ../src/core/gui.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/gui.cpp -o $@

../../obj/engine/Release/engine.o: ../src/core/engine.cpp
	@echo '$(CYAN)Building Object ../src/core/engine.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/engine.cpp -o $@

../../obj/engine/Release/device.o: ../src/core/renderer/device.cpp
	@echo '$(CYAN)Building Object ../src/core/renderer/device.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/renderer/device.cpp -o $@

../../obj/engine/Release/renderer.o: ../src/core/renderer/renderer.cpp
	@echo '$(CYAN)Building Object ../src/core/renderer/renderer.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/renderer/renderer.cpp -o $@

../../obj/engine/Release/allocator.o: ../src/core/renderer/allocator.cpp
	@echo '$(CYAN)Building Object ../src/core/renderer/allocator.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../lib/io -I../inc -I../inc/core -I../inc/imgui -I../inc/shared -I../inc/types -I../inc/SDL2 ../src/core/renderer/allocator.cpp -o $@


__PREBUILD:
	



__PRELINK:
	


endif

endif
